apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: kmsacr.azurecr.io/fastapi-demo:v1  # 여기 본인 ACR 이미지 주소
        ports:
        - containerPort: 80

