name: build-and-bump

permissions:
  contents: read
  # (OIDC 안 쓸 거면 id-token은 없어도 됩니다. 혹시 OIDC 쓸 땐 id-token: write 필요)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: fastapi-demo
  DEPLOY_REPO: min9ss/deploy-repo
  VALUES_FILE: envs/dev/values.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) 앱 레포 체크아웃
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Debug secrets presence (values hidden)
        run: |
          missing=0
          if [ -z "${{ secrets.AZ_CLIENT_ID }}" ]; then
            echo "::error::AZ_CLIENT_ID is MISSING"; missing=1; else echo "AZ_CLIENT_ID is present"; fi
          if [ -z "${{ secrets.AZ_CLIENT_SECRET }}" ]; then
            echo "::error::AZ_CLIENT_SECRET is MISSING"; missing=1; else echo "AZ_CLIENT_SECRET is present"; fi
          if [ -z "${{ secrets.AZ_TENANT_ID }}" ]; then
            echo "::error::AZ_TENANT_ID is MISSING"; missing=1; else echo "AZ_TENANT_ID is present"; fi
          if [ -z "${{ secrets.AZ_SUBSCRIPTION_ID }}" ]; then
            echo "::error::AZ_SUBSCRIPTION_ID is MISSING"; missing=1; else echo "AZ_SUBSCRIPTION_ID is present"; fi
          exit $missing

      # 2) Azure 로그인 (4개 시크릿 방식)
      - name: Azure Login
        env:
          AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        run: |
          set -e
          az login --service-principal \
            -u "$AZ_CLIENT_ID" \
            -p "$AZ_CLIENT_SECRET" \
            --tenant "$AZ_TENANT_ID"
          az account set --subscription "$AZ_SUBSCRIPTION_ID"
          az account show
  

      # 3) ACR 로그인
      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # 4) 이미지 빌드 & 푸시
      - name: Build and Push Docker Image
        run: |
          SHA=${GITHUB_SHA::7}
          echo "NEW_TAG=$SHA" >> $GITHUB_ENV

          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$SHA
          docker build -t $IMAGE .
          docker push $IMAGE

          # (선택) latest 태그도 푸시
          docker tag $IMAGE ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      # 5) 배포 레포 체크아웃
      - name: Checkout deploy repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DEPLOY_REPO }}
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          path: deploy-repo

      # 6) values.yaml 수정
      - name: Update values.yaml
        working-directory: deploy-repo
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq -i '.image.tag = env(NEW_TAG)' ${{ env.VALUES_FILE }}
          echo "Changed values.yaml:"
          cat ${{ env.VALUES_FILE }}

      # 7) 커밋 & 푸시 (git 128 방지: origin을 PAT로 고정 + 유니크 브랜치)
      - name: Commit and Push changes
        working-directory: deploy-repo
        env:
          REMOTE: https://${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/${{ env.DEPLOY_REPO }}.git
        run: |
          set -e
          git remote set-url origin "$REMOTE"
          git fetch origin

          # 변경 없으면 PR 스킵
          if git diff --quiet -- ${{ env.VALUES_FILE }}; then
            echo "SKIP_PR=true" >> $GITHUB_ENV
            exit 0
          fi

          BRANCH=bump/${{ env.IMAGE_NAME }}-${{ env.NEW_TAG }}-${GITHUB_RUN_ID}
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add ${{ env.VALUES_FILE }}
          git commit -m "bump ${{ env.IMAGE_NAME }} to ${{ env.NEW_TAG }}"
          git push origin "$BRANCH"

      # 8) PR 생성 (스킵 조건 반영)
      - name: Create Pull Request
        if: env.SKIP_PR != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          branch: bump/${{ env.IMAGE_NAME }}-${{ env.NEW_TAG }}-${{ github.run_id }}
          base: main
          title: "bump ${{ env.IMAGE_NAME }} to ${{ env.NEW_TAG }}"
          body: |
            - Image: `${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.NEW_TAG }}`
            - Updated values file: `${{ env.VALUES_FILE }}`

